/**
 * models/Message.js
 *
 * WHY: This is the most data-rich model. Every assistant message stores
 * ragMetadata — the full audit trail of how the answer was produced:
 * which law chunks were used, similarity scores, and timing for each
 * step of the pipeline.
 *
 * This data powers:
 * - Citation cards in the UI
 * - Performance monitoring
 * - Debugging hallucinations (compare answer to source chunks)
 */

const mongoose = require('mongoose');

// Sub-schema for a single law citation (one matched Pinecone vector)
const citationSchema = new mongoose.Schema(
  {
    vectorId: String, // e.g. "BNS_section_103_2024"
    lawName: String, // e.g. "Bharatiya Nyaya Sanhita 2023"
    lawCode: String, // e.g. "BNS"
    section: String, // e.g. "103"
    sectionTitle: String, // e.g. "Punishment for murder"
    lastAmended: String, // e.g. "2023-12-25"
    sourceUrl: String, // e.g. "https://egazette.gov.in/..."
    isRepealed: { type: Boolean, default: false },
    replacedBy: String, // e.g. "BNS_section_103" if this is an IPC entry
    replaces: String, // e.g. "IPC_section_302" if this is a BNS entry
    similarityScore: Number, // Pinecone cosine similarity score (0–1)
  },
  { _id: false } // Don't create _id for each citation sub-doc
);

// Sub-schema for RAG pipeline timing (helps us detect slow steps)
const timingsSchema = new mongoose.Schema(
  {
    queryEmbeddingMs: Number,
    pineconeQueryMs: Number,
    geminiGenerationMs: Number,
    totalMs: Number,
  },
  { _id: false }
);

const messageSchema = new mongoose.Schema(
  {
    sessionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'ChatSession',
      required: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    role: {
      type: String,
      enum: ['user', 'assistant'],
      required: true,
    },
    content: {
      type: String,
      required: true,
      maxlength: 10000,
    },
    // Language auto-detected from user message (carries over to assistant reply)
    detectedLanguage: {
      type: String,
      default: 'en',
    },
    // Only populated for role === 'assistant' messages
    ragMetadata: {
      confidenceScore: Number, // Top matched chunk's similarity score
      citations: [citationSchema],
      timings: timingsSchema,
      // True for messages generated by the legal notice upload pipeline
      // WHY in schema: without this, Mongoose strict mode silently drops it
      isNoticeAnalysis: { type: Boolean, default: false },
      // Structural fraud-signal check result — only present on notice messages
      legitimacyCheck: {
        riskLevel:            { type: String, enum: ['low', 'medium', 'high'] },
        redFlags:             [String],
        legitimacyIndicators: [String],
        summary:              String,
      },
    },
    // True if any matched chunk had is_repealed: true
    // WHY: We denormalise this flag so the UI can show a warning badge
    // without parsing all citations every render
    hasRepealedWarning: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

// Compound index: get all messages in a session, sorted chronologically
messageSchema.index({ sessionId: 1, createdAt: 1 });
messageSchema.index({ userId: 1 });

module.exports = mongoose.model('Message', messageSchema);
